# Generated by Django 4.0.6 on 2022-07-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('uri', models.CharField(max_length=150)),
                ('arte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arte_artista.arte')),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arte_artista.multimedia')),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=450)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arte_artista.portafolio')),
            ],
        ),
        migrations.CreateModel(
            name='Arte_Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arte_artista.arte')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arte_artista.artista')),
            ],
        ),
    ]
